### ISSUE TITLE
Cape Hatteras (CAHA) Boundary Update

### ISSUE THREAD

**Issue by dothandave** [nationalparkservice/data#4]
Need to update boundary for CAHA to emailed shapefile.

**Comment by makella** [comment]
@dothandave can you let us know where the data are so we can update for Park Tiles as well?

Thanks! mamata

**Comment by makella** [comment]
@dothandave you can post that information in Park Tiles issues:  https://github.com/nationalparkservice/park-tiles/issues?state=open

**Comment by makella** [comment]
@dothandave disregard! @jimmyrocks told me it is up on cartodb.
