### ISSUE TITLE
Are data sets available for any parks in Michigan

### ISSUE THREAD

**Issue by vielmetti** [nationalparkservice/data#5]
specifically

Pictured Rocks National Lakeshore
Isle Royale National Park

and specifically also in GeoJSON format.

thanks!

(and if there's a better place to ask this let me know)

**Comment by nateirwin** [comment]
Hello,

The official source for vetted National Park Service data is the NPS Data Store: https://irma.nps.gov/App/Reference/Search. You may want to check there, although I doubt any of the datasets are in GeoJSON format. QGIS is a good way to convert from the types of file formats you will likely see in the Data Store (shapefile, file geodatabase, etc.) to GeoJSON.
